"""
stratum_threshold_distances.py
For each stratum, compute BFS distance to the global threshold Z_62.

Questions:
1. Is B_31 uniformly distance-1 from Z_62?
2. Does T_75 have a gradient (some elements close, some far)?
3. Does the distance distribution in T_75 correlate with GUE statistics?
4. What is the internal distance structure of Z_62 to the Weinberg 26?
"""
import sys
import numpy as np
from collections import Counter, defaultdict

sys.path.insert(0, '.')
from psl27_core import build_group, classify_strata, mat_key

print("=" * 72)
print("  STRATUM THRESHOLD DISTANCES: BFS TO Z_62")
print("=" * 72)

elems, e2i, mul, inv_table, ords, ID = build_group()
B_31, Z_62, T_75, z3, z3sq, W26, S3 = classify_strata(
    elems, e2i, mul, inv_table, ords, ID)

generators = list(range(168))  # all group elements as potential multipliers

# =========================================================================
# BFS distance from element e to target set, using RIGHT multiplication
# by all group elements. Distance = min word length to reach target.
# =========================================================================

def bfs_distance_to_set(start, target_set, mul_table):
    """
    BFS distance from start element to nearest element of target_set.
    Edges: right-multiply by any group element (= Cayley graph distance).

    But full Cayley graph has diameter 1 (every element is g*h for some h).
    So we use GENERATORS instead — minimal generating set of PSL(2,7).
    """
    from collections import deque
    if start in target_set:
        return 0
    visited = {start}
    queue = deque([(start, 0)])
    while queue:
        current, dist = queue.popleft()
        for gen in gen_set:
            # Right multiply
            nxt = mul_table[current, gen]
            if nxt in target_set:
                return dist + 1
            if nxt not in visited:
                visited.add(nxt)
                queue.append((nxt, dist + 1))
            # Left multiply
            nxt2 = mul_table[gen, current]
            if nxt2 in target_set:
                return dist + 1
            if nxt2 not in visited:
                visited.add(nxt2)
                queue.append((nxt2, dist + 1))
    return float('inf')


# Find a minimal generating set for PSL(2,7)
# PSL(2,7) is generated by an element of order 2 and an element of order 3
# (or order 2 and order 7). Let's find a small generating set.
def find_generators(mul_table, ords, ID):
    """Find a minimal generating set for PSL(2,7)."""
    from collections import deque
    # Try pairs (order 2, order 3) and (order 2, order 7)
    ord2 = [i for i in range(168) if ords[i] == 2]
    ord3 = [i for i in range(168) if ords[i] == 3]
    ord7 = [i for i in range(168) if ords[i] == 7]

    for a in ord2:
        for b in ord3[:5]:  # try a few
            # Check if {a, b} generates the full group
            generated = {ID}
            frontier = {ID, a, b}
            while frontier - generated:
                generated.update(frontier)
                new = set()
                for x in frontier:
                    for g in [a, b]:
                        new.add(mul_table[x, g])
                        new.add(mul_table[g, x])
                frontier = new - generated
            if len(generated) == 168:
                return [a, b]

    # Fallback: try order 2 + order 7
    for a in ord2:
        for b in ord7[:3]:
            generated = {ID}
            frontier = {ID, a, b}
            while frontier - generated:
                generated.update(frontier)
                new = set()
                for x in frontier:
                    for g in [a, b]:
                        new.add(mul_table[x, g])
                        new.add(mul_table[g, x])
                frontier = new - generated
            if len(generated) == 168:
                return [a, b]

    return None

print("\nFinding minimal generating set...")
gen_pair = find_generators(mul, ords, ID)
if gen_pair:
    print(f"  Generators: {gen_pair} (orders {[int(ords[g]) for g in gen_pair]})")
else:
    print("  WARNING: Could not find 2-element generating set, using order-2 + order-3 + order-7")
    gen_pair = [next(i for i in range(168) if ords[i] == 2),
                next(i for i in range(168) if ords[i] == 3),
                next(i for i in range(168) if ords[i] == 7)]

# Include generators AND their inverses
gen_set = set()
for g in gen_pair:
    gen_set.add(g)
    gen_set.add(inv_table[g])
gen_set = sorted(gen_set)
print(f"  Generator set (with inverses): {gen_set}")

# Verify they generate the full group
def verify_generation(gens, mul_table, ID):
    generated = {ID}
    frontier = set(gens) | {ID}
    while frontier - generated:
        generated.update(frontier)
        new = set()
        for x in frontier:
            for g in gens:
                new.add(mul_table[x, g])
                new.add(mul_table[g, x])
        frontier = new - generated
    return len(generated)

gen_size = verify_generation(gen_set, mul, ID)
print(f"  Generators produce {gen_size}/168 elements: {'OK' if gen_size == 168 else 'FAIL'}")

# =========================================================================
# 1. BFS DISTANCE FROM B_31 TO Z_62
# =========================================================================
print("\n" + "-" * 72)
print("  1. BFS DISTANCE: B_31 -> Z_62")
print("-" * 72)

dist_B = {}
for e in sorted(B_31):
    dist_B[e] = bfs_distance_to_set(e, Z_62, mul)

b_dist_counter = Counter(dist_B.values())
print(f"\n  Distance distribution (B_31 -> Z_62):")
for d in sorted(b_dist_counter.keys()):
    print(f"    distance {d}: {b_dist_counter[d]} elements")

print(f"\n  Is B_31 uniformly distance-1? {all(v == 1 for v in dist_B.values())}")
print(f"  Mean distance: {np.mean(list(dist_B.values())):.3f}")
print(f"  Max distance:  {max(dist_B.values())}")
print(f"  Min distance:  {min(dist_B.values())}")

# =========================================================================
# 2. BFS DISTANCE FROM T_75 TO Z_62
# =========================================================================
print("\n" + "-" * 72)
print("  2. BFS DISTANCE: T_75 -> Z_62")
print("-" * 72)

dist_T = {}
for e in sorted(T_75):
    dist_T[e] = bfs_distance_to_set(e, Z_62, mul)

t_dist_counter = Counter(dist_T.values())
print(f"\n  Distance distribution (T_75 -> Z_62):")
for d in sorted(t_dist_counter.keys()):
    print(f"    distance {d}: {t_dist_counter[d]} elements")

print(f"\n  Does T_75 have a gradient? {len(t_dist_counter) > 1}")
print(f"  Mean distance: {np.mean(list(dist_T.values())):.3f}")
print(f"  Max distance:  {max(dist_T.values())}")
print(f"  Min distance:  {min(dist_T.values())}")

# Break down T_75 distances by element order
print(f"\n  T_75 distances by element order:")
t75_by_order = defaultdict(list)
for e in T_75:
    t75_by_order[int(ords[e])].append(dist_T[e])
for o in sorted(t75_by_order.keys()):
    dists = t75_by_order[o]
    print(f"    order {o}: {len(dists)} elems, mean dist = {np.mean(dists):.3f}, "
          f"dist distribution = {dict(Counter(dists))}")

# =========================================================================
# 3. INTERNAL DISTANCES: Z_62 -> WEINBERG 26
# =========================================================================
print("\n" + "-" * 72)
print("  3. INTERNAL DISTANCE: Z_62 -> WEINBERG 26")
print("-" * 72)

dist_Z_to_W = {}
for e in sorted(Z_62):
    if e in W26:
        dist_Z_to_W[e] = 0
    else:
        dist_Z_to_W[e] = bfs_distance_to_set(e, W26, mul)

z_dist_counter = Counter(dist_Z_to_W.values())
print(f"\n  Distance distribution (Z_62 -> Weinberg 26):")
for d in sorted(z_dist_counter.keys()):
    print(f"    distance {d}: {z_dist_counter[d]} elements")

print(f"\n  Non-Weinberg elements of Z_62: {len(Z_62) - len(W26)}")
non_weinberg = Z_62 - W26
nw_dists = [dist_Z_to_W[e] for e in non_weinberg]
print(f"  Non-Weinberg distance distribution: {dict(Counter(nw_dists))}")
print(f"  Non-Weinberg mean distance to W26: {np.mean(nw_dists):.3f}")

# Non-Weinberg by order
print(f"\n  Non-Weinberg Z_62 by order:")
nw_by_order = defaultdict(list)
for e in non_weinberg:
    nw_by_order[int(ords[e])].append(dist_Z_to_W[e])
for o in sorted(nw_by_order.keys()):
    dists = nw_by_order[o]
    print(f"    order {o}: {len(dists)} elems, dist distribution = {dict(Counter(dists))}")

# =========================================================================
# 4. CORRELATION: T_75 DISTANCE VS S_3-ORBIT STRUCTURE
# =========================================================================
print("\n" + "-" * 72)
print("  4. T_75 DISTANCE VS S_3-ORBIT STRUCTURE")
print("-" * 72)

# Compute S_3 orbits of T_75
remaining = set(T_75)
orbits_t75 = []
while remaining:
    x = min(remaining)
    orbit = set()
    for g in S3:
        orbit.add(mul[g, mul[x, inv_table[g]]])
    orbits_t75.append(sorted(orbit))
    remaining -= orbit
orbits_t75.sort(key=lambda o: (len(o), o[0]))

print(f"\n  {'Orb':>4} {'Size':>5} {'Orders':>10} {'Mean dist':>10} {'Dist range':>12} {'Dists'}")
print(f"  {'-'*4} {'-'*5} {'-'*10} {'-'*10} {'-'*12} {'-'*20}")
for i, orb in enumerate(orbits_t75):
    orb_dists = [dist_T[e] for e in orb]
    orb_ords = sorted(set(int(ords[e]) for e in orb))
    print(f"  {i+1:4d} {len(orb):5d} {str(orb_ords):>10} {np.mean(orb_dists):10.3f} "
          f"{min(orb_dists)}-{max(orb_dists):>8} {dict(Counter(orb_dists))}")

# Are order-4 elements (bridge elements) the closest T_75 to Z_62?
order4_in_t75 = [e for e in T_75 if ords[e] == 4]
if order4_in_t75:
    o4_dists = [dist_T[e] for e in order4_in_t75]
    other_dists = [dist_T[e] for e in T_75 if ords[e] != 4]
    print(f"\n  Order-4 bridge elements in T_75: {len(order4_in_t75)}")
    print(f"  Order-4 mean distance: {np.mean(o4_dists):.3f}")
    print(f"  Other elements mean distance: {np.mean(other_dists):.3f}")
    print(f"  Order-4 closer to Z_62? {np.mean(o4_dists) < np.mean(other_dists)}")

# =========================================================================
# 5. DISTANCE MATRIX: CROSS-STRATUM STRUCTURE
# =========================================================================
print("\n" + "-" * 72)
print("  5. CROSS-STRATUM DISTANCE SUMMARY")
print("-" * 72)

# Also compute B_31 to T_75 distance
dist_B_to_T = {}
for e in sorted(B_31):
    dist_B_to_T[e] = bfs_distance_to_set(e, T_75, mul)

bt_counter = Counter(dist_B_to_T.values())
print(f"\n  B_31 -> T_75 distance distribution: {dict(sorted(bt_counter.items()))}")
print(f"  B_31 -> T_75 mean distance: {np.mean(list(dist_B_to_T.values())):.3f}")

print(f"\n  Summary:")
print(f"  {'':>15} {'-> Z_62':>10} {'-> T_75':>10}")
print(f"  {'B_31 mean':>15} {np.mean(list(dist_B.values())):10.3f} {np.mean(list(dist_B_to_T.values())):10.3f}")
print(f"  {'T_75 mean':>15} {np.mean(list(dist_T.values())):10.3f} {'(self)':>10}")

# Internal distances
print(f"  {'Z_62->W26':>15} {np.mean(list(dist_Z_to_W.values())):10.3f}")

# =========================================================================
# 6. DIAMETER AND CONNECTIVITY
# =========================================================================
print("\n" + "-" * 72)
print("  6. CAYLEY GRAPH DIAMETER")
print("-" * 72)

# Compute diameter of the Cayley graph (max BFS distance between any two elements)
from collections import deque

def bfs_all_distances(start, gen_set, mul_table):
    """BFS from start, return dict of distances to all reachable elements."""
    dist = {start: 0}
    queue = deque([start])
    while queue:
        current = queue.popleft()
        for g in gen_set:
            for nxt in [mul_table[current, g], mul_table[g, current]]:
                if nxt not in dist:
                    dist[nxt] = dist[current] + 1
                    queue.append(nxt)
    return dist

# Compute from a few representative elements to find diameter
sample_elems = [ID] + sorted(B_31)[:3] + sorted(T_75)[:3] + sorted(Z_62)[:3]
max_dist = 0
for e in sample_elems:
    d = bfs_all_distances(e, gen_set, mul)
    if len(d) < 168:
        print(f"  WARNING: BFS from {e} only reached {len(d)} elements!")
    md = max(d.values())
    if md > max_dist:
        max_dist = md

print(f"  Cayley graph diameter (lower bound from {len(sample_elems)} samples): {max_dist}")
print(f"  Generators used: {gen_set}")

# Full diameter
print(f"\n  Computing full diameter...")
diameter = 0
for e in range(168):
    d = bfs_all_distances(e, gen_set, mul)
    md = max(d.values())
    if md > diameter:
        diameter = md
print(f"  Cayley graph diameter (exact): {diameter}")

# =========================================================================
# SUMMARY
# =========================================================================
print("\n" + "=" * 72)
print("  SUMMARY: THRESHOLD DISTANCES")
print("=" * 72)

b_mean = np.mean(list(dist_B.values()))
t_mean = np.mean(list(dist_T.values()))
z_w_mean = np.mean(list(dist_Z_to_W.values()))

print(f"""
  B_31 -> Z_62: mean = {b_mean:.3f}, uniform = {len(set(dist_B.values())) == 1}
  T_75 -> Z_62: mean = {t_mean:.3f}, gradient = {len(set(dist_T.values())) > 1}
  Z_62 -> W26:  mean = {z_w_mean:.3f}

  Depth ratios:
    D(B)/D(Z_int) = {b_mean/z_w_mean:.4f} if Z_int != 0
    D(T)/D(Z_int) = {t_mean/z_w_mean:.4f} if Z_int != 0
    D(T)/D(B) = {t_mean/b_mean:.4f} if B != 0

  Cayley graph diameter: {diameter}

  h-dual predictions:
    h*(E6) : h*(B6) : h*(C6) = 12 : 11 : 7
    Ratio 12/11 = {12/11:.4f}
    Ratio 12/7  = {12/7:.4f}
    Ratio 11/7  = {11/7:.4f}
""")
